Implement policy finding candidates to be slashed
bosagora/agora pull request #1340
Opened 2020-11-09 11:33 UTC by linked0

This creates the policy manager class for slashing and defined the base criteria where a validator will be slashed as the first step of issue 1076. As a result of the whiteboarding session, we start with 10k on the missing pre-image, effective immediately. I will implement the feature imposing 10K BOA on the misbehaving validator in other PR.

Part of #1076

2020-11-10 02:14 UTC, AndrejMitrovic requested changes
Just a few issues.

2020-11-10 02:14 UTC, AndrejMitrovic commented on source/agora/consensus/SlashPolicy.d
> +        return this.penalty_amount;
I'm not sure this belongs here. Will this class be in charge of slashing? It seems not, because it has a public method `getSlashCandidates`, so it will be another class which does the actual slashing right? This one is just about selecting the candidates.

But then this class doesn't need to store the penalty amount, the other class will be in charge of that.

2020-11-10 02:14 UTC, AndrejMitrovic commented on source/agora/consensus/EnrollmentManager.d
> +    PreImageInfo[] getAllPreimages () @trusted nothrow
`public`. And please use `@safe` and make the function in `ValidatorSet` also `@safe`.

2020-11-10 02:14 UTC, AndrejMitrovic commented on source/agora/consensus/state/ValidatorSet.d
> +    PreImageInfo[] getAllPreimages () @trusted nothrow
`public` and `@safe`

2020-11-10 02:14 UTC, AndrejMitrovic commented on source/agora/consensus/SlashPolicy.d
> +            block_height = current block height
```suggestion
            height = current block height
```

2020-11-10 02:14 UTC, AndrejMitrovic commented on source/agora/consensus/SlashPolicy.d
> +                finder(preimage.enroll_key, utxo_value);
UTXOFinder returns a boolean, please use it here instead of comparing with `UTXO.init`.

2020-11-10 02:14 UTC, AndrejMitrovic commented on source/agora/consensus/SlashPolicy.d
> +        this.penalty_amount = Amount(100_000_000_000);
This ultimately belongs in the `ConsensusParams`. However, since this is WIP you may keep it hardcoded for now.

2020-11-10 02:28 UTC, linked0 commented on source/agora/consensus/SlashPolicy.d
> +        this.penalty_amount = Amount(100_000_000_000);
Currently, the `SlashPolicy` class manages the amount but it can be moved into `ConsensusParams` as you commented. It will be done on other PR.

2020-11-10 02:28 UTC, linked0 commented on source/agora/consensus/EnrollmentManager.d
> +    PreImageInfo[] getAllPreimages () @trusted nothrow
My mistake. I will update it.

2020-11-10 02:28 UTC, linked0 commented on source/agora/consensus/state/ValidatorSet.d
> +    PreImageInfo[] getAllPreimages () @trusted nothrow
Ditto.

2020-11-10 02:28 UTC, linked0 commented on source/agora/consensus/SlashPolicy.d
> +            block_height = current block height
Will update it.

2020-11-10 02:29 UTC, linked0 commented on source/agora/consensus/SlashPolicy.d
> +                finder(preimage.enroll_key, utxo_value);
Ditto

2020-11-10 02:35 UTC, linked0 commented on source/agora/consensus/SlashPolicy.d
> +        return this.penalty_amount;
The description of the class is confusing. I will update it. Actually this class is in charge of managing slashing policy which determine the condition where the slashing must be done.

2021-01-13 02:47 UTC, linked0 commented
This PR is not needed anymore.

2021-01-13 02:47 UTC, closed without merging