Enable enrollments empty check in GenesisBlock
bosagora/agora pull request #1387
Opened 2020-11-27 04:03 UTC by TrustHenry

Genesis blocks must contain enrollments.
Genesis blocks without enrollments cannot create the next block.

Related to #1361

2020-11-27 04:04 UTC, TrustHenry commented
@Geod24 The first block start policy is required.
https://github.com/bpfkorea/agora/issues/1361#issuecomment-734531195

2020-11-27 05:06 UTC, linked0 reviewed
Good start!
One request and there's an error about Genesis block having no enrollment on the CI build. Would you please check it?

2020-11-27 05:06 UTC, linked0 commented on source/agora/consensus/validation/Block.d
> +        return "GenesisBlock: Does not include enrollments";
How about expressing in the same format as other messages, like "No enrollment in the block"

2020-11-27 05:17 UTC, TrustHenry commented on source/agora/consensus/validation/Block.d
> +        return "GenesisBlock: Does not include enrollments";
It's good, the sentence.

2020-11-27 05:19 UTC, TrustHenry commented
> One request and there's an error about Genesis block having no enrollment on the CI build. Would you please check it?

It's written on the top.
This has been blocked due to the following issues.
#1361 (comment)

2020-11-28 01:39 UTC, AndrejMitrovic commented
You can just add a temporary fake enrollment to the coinnet genesis block.

The real enrollments and transactions will be defined later.

2020-12-08 10:14 UTC, TrustHenry commented
Ready for review.

2020-12-09 00:40 UTC, TrustHenry commented
> You can just add a temporary fake enrollment to the coinnet genesis block.

@AndrejMitrovic Yes, I did temporarily defined enrollments and reconstructed Genesis blocks.

2020-12-09 03:12 UTC, AndrejMitrovic requested changes
Just a few comments, almost ready to go.

2020-12-09 03:12 UTC, AndrejMitrovic commented on source/agora/consensus/validation/Block.d
>      // If there are no enrollments, return them here early.
Outdated. You can just remove this comment.

2020-12-09 03:12 UTC, AndrejMitrovic commented on source/agora/consensus/validation/Block.d
> +        block.txs = null;
It's already `null`, can you remove this line?

2020-12-09 03:12 UTC, AndrejMitrovic commented on source/agora/consensus/validation/Block.d
> +        return "GenesisBlock: No enrollment in the block";
```suggestion
        return "GenesisBlock: No enrollments in the block";
```

More proper English. :)

2020-12-09 03:50 UTC, TrustHenry commented
@AndrejMitrovic Thanks for the reviews. All fixed it.

2020-12-09 04:28 UTC, AndrejMitrovic approved these changes

2020-12-09 04:28 UTC, merged

2020-12-11 03:03 UTC, AndrejMitrovic commented
I wish you kept it the same layout like the test genesis. In the test genesis the first tx is the freeze, in yours its the pay.

It's ok, I'll fix it myself.

2020-12-11 04:37 UTC, TrustHenry commented
> I wish you kept it the same layout like the test genesis. In the test genesis the first tx is the freeze, in yours its the pay.
> 
> It's ok, I'll fix it myself.

The order of transactions has changed because of the transaction hash sorting.
Is it weird?

2020-12-11 04:41 UTC, AndrejMitrovic commented
No it's ok, it was just a little harder to create the enrollments. It's ok, thank you.

2020-12-11 04:42 UTC, TrustHenry commented
> No it's ok, it was just a little harder to create the enrollments. It's ok, thank you.

Yes, it was hard to make the enrolments. :)