Add a config options to allow a less validators in the test network
bosagora/agora pull request #1593
Opened 2021-02-03 06:45 UTC by Geod24

Pretty straightforward, and will make sure that the network doesn't start by slashing 5 validators to make progress.

2021-02-03 06:45 UTC, Geod24 commented
CC @MichaelKim20 : Once we merge this, I'll make a docker-compose file so you can have a lightweight test env.

2021-02-03 07:03 UTC, linked0 approved these changes
LGTM

2021-02-03 07:04 UTC, hewison-chris requested changes
Exception message update.

2021-02-03 07:04 UTC, hewison-chris commented on source/agora/common/Config.d
> +        throw new Exception("Cannot use 'node.limit_test_validator' without 'consensus.config' set to 'true'");
```suggestion
        throw new Exception("Cannot use 'node.limit_test_validator' without 'testing' set to 'true'");
```

2021-02-03 07:15 UTC, hewison-chris commented
Also typo in commit message.

2021-02-03 07:17 UTC, Geod24 commented
Upadted

2021-02-03 07:24 UTC, hewison-chris approved these changes
Commit title still has typo though.

2021-02-03 07:26 UTC, hewison-chris commented on source/agora/node/FullNode.d
> +                return TESTNET.GenesisBlock;
So we use a different Genesis Block when we limit the validators?

2021-02-03 07:27 UTC, hewison-chris commented on source/agora/node/FullNode.d
> +                return TESTNET.GenesisBlock;
Sorry I see now.

2021-02-03 07:28 UTC, Geod24 commented
> Commit title still has typo though.

There were too many of them.

2021-02-03 07:48 UTC, merged

2021-02-04 01:05 UTC, MichaelKim20 commented
@Geod24 The blocks are not being created, so could you check if the environment I used is correct?
[test.zip](https://github.com/bpfkorea/agora/files/5922478/test.zip)

2021-02-04 01:07 UTC, Geod24 commented
No it's not correct. I gave you a correct one yesterday: https://github.com/Geod24/rns-test-env

2021-02-04 02:16 UTC, TrustHenry commented
`agora_1   | 2021-02-04 02:06:10,250 Fatal [agora.consensus.protocol.Nominator] - tryNominate(): Invalid consensus data: Enrollment: Insufficient number of active validators. Data: { tx_set: [0x443eeee989f9c36d92399195f88f60b3d47534e7d16d138dbf6394f2c14ba8d24d647aa1dece131176cbb968342cfa2873601252f1165e9a47b1794aaa308705], enrolls: [], missing_validators: [], timestamp: 1612404370 }`

Verification is not passing at block height 19.
https://github.com/bpfkorea/agora/blob/af1063749aab3c70a8b9b1ebc5ee768101b21bcc/source/agora/node/Ledger.d#L773-L774

2021-02-04 02:18 UTC, Geod24 commented
That's https://github.com/bpfkorea/agora/issues/1500

2021-02-04 02:25 UTC, hewison-chris commented
> #1500

Actually #1500 is for height 1999 on cycle of 20. Looks like the problem @TrustHenry is reporting is due to a minimum number of validators being checked before the last block of the cycle.

2021-02-04 04:06 UTC, kchulj commented on source/agora/consensus/data/genesis/Test.d
> +            // NODE6
The comment was deleted [here](https://github.com/bpfkorea/agora/commit/0b03ccfcabe3426142800263550e58e43523b234#diff-777ad51a9f1968fe0167b8879a60b890b67a5202d961561b03bd6a1c53592ea1) :/