Make BlockStorage.updateBlockMultiSig accepts the sig and bitfield
bosagora/agora pull request #1671
Opened 2021-02-18 09:14 UTC by Geod24

Instead of passing the whole block and serializing it,
just pass the fields to update along with the height
(to locate the block) and the hash (to check we have the right one).

2021-02-19 05:19 UTC, Geod24 commented
So, this fails because the `Height` is variably-serialized.

2021-02-19 06:07 UTC, hewison-chris commented
> So, this fails because the `Height` is variably-serialized.

Look like a compilation error in `agora/tests/unit/BlockStorageMultiSig.d`

2021-02-19 06:16 UTC, Geod24 commented
Should be fixed now

2021-02-19 06:55 UTC, hewison-chris requested changes
Not quite ready yet.

2021-02-19 06:55 UTC, hewison-chris commented on tests/unit/BlockStorageMultiSig.d
> +    iota(1, BlockCount).each!((h) {
I have still seen cases where compile fails and it doesn't give the line number of the actual line that causes the problem. Only solution I think is to call inner function in lambda.

2021-02-19 06:55 UTC, hewison-chris commented on tests/unit/BlockStorageMultiSig.d
> +        storage.updateBlockSig(Height(h), block2.hashFull(), SIG2, block2.header.validators);
This test fails now with `Hash of block to update differs from the expected one`

2021-02-22 06:01 UTC, Geod24 commented
Fixed

2021-02-22 06:42 UTC, hewison-chris approved these changes
LGTM

2021-02-22 06:42 UTC, merged