Don't compare full blocks in the tests
bosagora/agora pull request #1757
Opened 2021-03-10 02:10 UTC by AndrejMitrovic

This makes the tests fail if the number
of signers doesn't exactly match between
the nodes - which is an expected occurence.

Instead just compare the block header hashes.

2021-03-10 02:14 UTC, hewison-chris requested changes
There are tests where this check is required though. Perhaps it can be made optional so only those tests that really need to check that all signatures are updated are in fact updated.

2021-03-10 02:15 UTC, AndrejMitrovic commented
> There are tests where this check is required though. Perhaps it can be made optional so only those tests that really need to check that all signatures are updated are in fact updated.

Yeah that makes sense.

Also I think signature propagation should be fixed. This is the Simple test that fails.

2021-03-10 04:48 UTC, AndrejMitrovic commented
> There are tests where this check is required though. Perhaps it can be made optional so only those tests that really need to check that all signatures are updated are in fact updated.

Which specific test is it?

2021-03-10 04:52 UTC, hewison-chris commented
> > There are tests where this check is required though. Perhaps it can be made optional so only those tests that really need to check that all signatures are updated are in fact updated.
> 
> Which specific test is it?

At least test.PeriodicCatchup.d and ValidatorCleanRestart should include this check.

2021-03-17 06:52 UTC, ferencdg commented on source/agora/test/Base.d
there might be a little bit of race condition here:

1. at line 1097 all clients has a block height of 10 including client 1, however client 1 is too busy to respond to the testing framework
3. all clients almost ready for accepting block with height 11
4. client 1 is finally able to report block height 10, so line 1097 returns
5. all clients accepted block with height 11
6. the assert will trigger at 1108

this has probably low chance to manifest, but we have big timing delays in test and small block creation(1sec/block I think)

2021-03-17 08:26 UTC, ferencdg commented on source/agora/test/Base.d
> +        all_blocks.sort!((a, b) => a.header.hashFull > b.header.hashFull);
we could get rid of the sorting/hashing and use some linear algorithm, if we want
(x is client_idxs.map!(idx => this.clients[idx].getAllBlocks())

```D
    int[] a = [1, 2, 3, 4];
    int[] b = [10, 20, 30, 40];
    int[] c = [100, 200, 300, 400];
    auto x = [a, b, c];
    iota(x.length).map!(i => x.transversal(i)).joiner.writeln;
```

2021-03-31 04:38 UTC, Geod24 commented
@AndrejMitrovic : Where are we on this ? I see some outstanding comments by @ferencdg .

2021-03-31 04:41 UTC, AndrejMitrovic commented
> At least test.PeriodicCatchup.d should include this check. I would also expect Simple to pass if given enough time.

Shouldn't 5 seconds be enough time? Should I just increase the value to 10?

2021-04-01 05:39 UTC, AndrejMitrovic commented
It seems that https://github.com/bosagora/agora/pull/1860/commits/5705e8ac1a83052ce7344384f96f5b3538d3bd1d covers this, I'll close my PR.

2021-04-01 05:39 UTC, closed without merging