Add ctor/dtor/copy/assign to std::vector bindings
bosagora/agora pull request #2081
Opened 2021-05-12 14:33 UTC by omerfirmak

2021-05-14 14:57 UTC, omerfirmak commented
```
submodules/serialization/source/agora/serialization/Serializer.d(698,17): Error: none of the overloads of __ctor are callable using a const object, candidates are:
source/scpd/Cpp.d(62,9):        scpd.types.Stellar_SCP.SCPBallot.CPPBindingMixin!(SCPBallot, true, true).this(CppCtor use)
source/scpd/Cpp.d(57,13):        scpd.types.Stellar_SCP.SCPBallot.CPPBindingMixin!(SCPBallot, true, true).this(uint, xvector!(ubyte, 4294967292u))
source/scpd/Cpp.d(73,9):        scpd.types.Stellar_SCP.SCPBallot.CPPBindingMixin!(SCPBallot, true, true).this(return ref scope inout(SCPBallot) rhs)

```

Shouldnt this work with `const` objects?

https://github.com/bosagora/agora/pull/2081/files#diff-2fff5f741967021f44722f88e37effa07123b287d13e843ff246b43d91a7d8d4R57-R60

2021-05-18 14:48 UTC, omerfirmak commented
This mostly works apart from a random crash that happens during GC finalizing a `vector`

2021-05-20 08:33 UTC, omerfirmak commented
> This mostly works apart from a random crash that happens during GC finalizing a `vector`

I can't reproduce this after a rebase but I don't see where we would GC allocate a `SCPEnvelope` anyways. Marking this ready for review for the time being.

2021-06-01 01:35 UTC, Geod24 requested changes

2021-06-01 01:35 UTC, Geod24 commented on source/scpd/Cpp.d
> +    void copyCtorCPPObject(T) (inout(T)* ptr, inout(T)* rhs);
Not sure why you would need `inout` for single-argument templated free functions, but I'm sure there's an horror story behind this :)

2021-06-01 01:35 UTC, Geod24 commented on source/scpd/Cpp.d
> +            @disable this();
```suggestion
            @disable this ();
```
👼

2021-06-01 01:35 UTC, Geod24 commented on source/scpd/Cpp.d
> +                __traits(getMember, this, field) = __traits(getMember, this, field).init;
Would it be possible to nest it in a dead condition just so that we don't run code that's not needed ?

2021-06-01 07:42 UTC, omerfirmak commented on source/scpd/Cpp.d
> +                __traits(getMember, this, field) = __traits(getMember, this, field).init;
Yeah that worked.

2021-06-01 07:42 UTC, omerfirmak commented
Rebased

2021-06-01 08:54 UTC, Geod24 approved these changes
Noice

2021-06-01 08:54 UTC, merged

2021-06-03 05:52 UTC, Geod24 commented
Reverted in #2143