Nominator: Be more verbose when we are not nominating
bosagora/agora pull request #2092
Opened 2021-05-16 09:52 UTC by Geod24

This should help better debug the reason(s) why a node is not nominating.
Currently we only see a bunch of 'Nominating X at Y" but nodes can get stuck.

2021-05-16 23:33 UTC, hewison-chris requested changes
LGTM just a tiny change requested

2021-05-16 23:33 UTC, hewison-chris commented on source/agora/consensus/protocol/Nominator.d
> +            this.log.trace("checkNominate(): No transaction to nominate yet");
```suggestion
            this.log.trace("prepareNominatingSet(): No transaction to nominate yet");
```

2021-05-16 23:45 UTC, linked0 approved these changes
LGTM

2021-05-17 00:06 UTC, Geod24 commented on source/agora/consensus/protocol/Nominator.d
> +            this.log.trace("checkNominate(): No transaction to nominate yet");
Good catch!

2021-05-17 00:06 UTC, Geod24 commented
Fixed method name

2021-05-17 00:10 UTC, hewison-chris approved these changes
LGTM

2021-05-17 00:22 UTC, kchulj approved these changes
LGTM

2021-05-17 01:44 UTC, merged