Registry: Relax rules to allow valid stakes to register
bosagora/agora pull request #2578
Opened 2021-10-13 09:14 UTC by omerfirmak

Builds on top of #2487

Fixes #2524

2021-10-13 09:15 UTC, omerfirmak commented
Alternative to commit#4 is to reject any validators that can not prove a stake, I am not completely sure which way is the right way to go. Feel free to comment.

2021-10-13 12:20 UTC, omerfirmak commented
Added the fix for #2576

2021-10-14 04:01 UTC, Geod24 requested changes

2021-10-14 04:01 UTC, Geod24 commented on source/agora/test/Base.d
> +        idx => fullNodeAddress(idx)).array ~ ["name.registry"];
Doesn't seem to belong to this commit ?

2021-10-14 04:01 UTC, Geod24 commented on source/agora/node/Registry.d
> +                .getEnrollments(last_height).canFind!(
Why do we check the enrollment pool ?

2021-10-14 04:01 UTC, Geod24 commented on source/agora/consensus/Ledger.d
> +    public UTXOCache utxo_set;
Just move `ValidatingLedger.peekUTXO` in `Ledger` and you can avoid exposing internals

2021-10-14 04:01 UTC, Geod24 commented on source/agora/node/Registry.d
> +        import std.range;
Move to top level

2021-10-14 06:12 UTC, omerfirmak commented on source/agora/node/Registry.d
> +                .getEnrollments(last_height).canFind!(
IIRC, that was how we discussed to go about this initially.

This way we don't need to do any checks on the frozen UTXO. If the enrollment is in the pool already, we know for sure that it satisfies all the requirements.

2021-10-14 08:13 UTC, Geod24 commented on source/agora/node/Registry.d
> +                .getEnrollments(last_height).canFind!(
But we still risk a race condition if the node's `Enrollment` doesn't make it to the registry.
Of course this can be trivially worked around by the client by sending the `Enrollment` first, but it looks like an un-needed edge case.

2021-10-14 08:13 UTC, Geod24 commented on source/agora/node/Registry.d
> +                .getEnrollments(last_height).canFind!(
I guess as a first step it would be fine, though, if the test suite goes green with this approach.

2021-10-14 09:34 UTC, omerfirmak commented on source/agora/node/Registry.d
> +                .getEnrollments(last_height).canFind!(
All green apart from the weird hang in between tests.

2021-10-15 00:42 UTC, Geod24 approved these changes

2021-10-15 00:42 UTC, merged