Make starting the nodes asynchronous
bosagora/agora pull request #310
Opened 2019-09-06 06:15 UTC by AndrejMitrovic

Previously what happened during boot in the tests was:

- for each node N in M:
=> node.start();
  => calls discover();
    => tries to reach other nodes
      => other nodes haven't had their start() method called yet, therefore they are not ready to communicate (blocks are not loaded from disk yet, etc)

This is all because in LocalRest after we send a message to a node's thread, we also wait for a response back.

With this PR the asynchronous starting of nodes is more thoroughly tested, and this also speeds up the tests a bit.

P.S.: Is there a better way to do this without using a `__gshared`?

Fixes #276

2019-09-10 08:51 UTC, Geod24 requested changes
I'd much rather have this done in `localrest`

2019-09-10 08:59 UTC, AndrejMitrovic commented
Yes me too, but it's a bit more involved. There is also a choice:

A) Should the calling thread just ignore the return value? If so, the called thread needs to know not to send the value back.
B) Should the calling thread eventually receive the value (via a callback), while not blocking the call?

2019-09-10 09:00 UTC, AndrejMitrovic commented
This PR doesn't have to be merged right now, it isn't necessarily required right now. So it can wait.

2020-02-25 03:56 UTC, AndrejMitrovic commented
> => other nodes haven't had their start() method called yet, therefore they are not ready to communicate (blocks are not loaded from disk yet, etc)

This part is no longer true. The block loading is done in the constructor.

2020-02-25 03:56 UTC, closed without merging