GC: Update our fork of the GC to upstream
bosagora/agora pull request #3163
Opened 2022-03-04 02:08 UTC by Geod24

```
This include the main following changes:
- Implementation of a `fork()` based GC, allowing to reduce pause time
  by relying on the COW behavior of pages of a forked process;
- A few refactoring made by myself, with the end goal of adding attributes
  to GC.stats, which accounts for a large portion of the trivial diff;
- Druntime commit 6558d800f8b4db57bb8954511b7c5987590a0480 which rename `hasFinalizer`
  to `doLoop` and removes the need for our `= true` changes thanks to `version (assert)`;
- A few other fixes, including the use of `emplace`, and a fix to `gc.bits`;
```

Here is the diff between `v0.x.x` and Druntime commit 99b04d8e5b509ab471b7d5ca83b85a7c4ecd9dd0 for the GC:
```diff
1,16c1,14
< /*******************************************************************************
<
<     A garbage collector that register memory allocations
<
<     This file was originally copied verbatim from druntime
<     (src/gc/impl/conservative/gc.d) at v2.095.0
<     (last commit 99b04d8e5b509ab471b7d5ca83b85a7c4ecd9dd0).
<
<     It was subsequently modified to include changes to allow tracking
<     allocations / deallocations using Tracy.
<
< *******************************************************************************/
<
< module agora.utils.gc.GC;
<
< import agora.utils.TracyAPI;
---
> /**
>  * Contains the garbage collector implementation.
>  *
>  * Copyright: Copyright Digital Mars 2001 - 2016.
>  * License:   $(HTTP www.boost.org/LICENSE_1_0.txt, Boost License 1.0).
>  * Authors:   Walter Bright, David Friedman, Sean Kelly
>  */
>
> /*          Copyright Digital Mars 2005 - 2016.
>  * Distributed under the Boost Software License, Version 1.0.
>  *    (See accompanying file LICENSE or copy at
>  *          http://www.boost.org/LICENSE_1_0.txt)
>  */
> module gc.impl.conservative.gc;
40,42c38,39
< import agora.utils.gc.bits;
< import agora.utils.gc.os;
<
---
> import gc.bits;
> import gc.os;
45d41
< import core.gc.registry;
53d48
< import core.time;
60a56
> import core.time;
114c110
< extern(C) pragma(crt_constructor) void _d_register_tracking_conservative_gc()
---
> extern(C) pragma(crt_constructor) void _d_register_conservative_gc()
117c113
<     registerGCFactory("tracking-conservative", &initialize);
---
>     registerGCFactory("conservative", &initialize);
120c116
< extern(C) pragma(crt_constructor) void _d_register_tracking_precise_gc()
---
> extern(C) pragma(crt_constructor) void _d_register_precise_gc()
123c119
<     registerGCFactory("tracking-precise", &initialize_precise);
---
>     registerGCFactory("precise", &initialize_precise);
405d400
<         ___tracy_emit_memory_alloc_callstack(p, size, 32, true);
411c406,407
<     override BlkInfo qalloc( size_t size, uint bits, const scope TypeInfo ti) nothrow
---
>
>     BlkInfo qalloc( size_t size, uint bits, const TypeInfo ti) nothrow
412a409
>
430a428
>
768d765
<         ___tracy_emit_memory_free(sentinel_add(p), true);
1244c1241
<     import agora.utils.gc.pooltable;
---
>     import gc.pooltable;
1282,1284c1279,1281
<                     &_d_gcx_tracking_atfork_prepare,
<                     &_d_gcx_tracking_atfork_parent,
<                     &_d_gcx_tracking_atfork_child);
---
>                     &_d_gcx_atfork_prepare,
>                     &_d_gcx_atfork_parent,
>                     &_d_gcx_atfork_child);
1637,1638c1634
<
<         auto ptr = size <= PAGESIZE/2 ? smallAlloc(size, alloc_size, bits, ti)
---
>         return size <= PAGESIZE/2 ? smallAlloc(size, alloc_size, bits, ti)
1640,1641d1635
<
<         return ptr;
2372d2365
<                         ___tracy_emit_memory_free(q, true);
2446c2439
<                         bool hasFinalizer = true;
---
>                         bool hasFinalizer = false;
2487d2479
<                                     ___tracy_emit_memory_free(sentinel_add(p), true);
2980c2972
<         extern(C) static void _d_gcx_tracking_atfork_prepare()
---
>         extern(C) static void _d_gcx_atfork_prepare()
2986c2978
<         extern(C) static void _d_gcx_tracking_atfork_parent()
---
>         extern(C) static void _d_gcx_atfork_parent()
2992c2984
<         extern(C) static void _d_gcx_tracking_atfork_child()
---
>         extern(C) static void _d_gcx_atfork_child()
4209,4214d4200
<             if (OPFAIL != current.find(p))
<             {
<                 debug(PRINTF) printf("Memory allocation without free'ing at %p\n", p);
<                 return;
<             }
<
```

Command used: 

Here is the diff for this PR:
```diff
1,13c1,8
< /*******************************************************************************
<
<     A garbage collector that register memory allocations
<
<     This file is based on Druntime's version (src/gc/impl/conservative/gc.d)
<     at v2.099.0-rc.1-57-gbadb3cef3 (badb3cef315b0a6a1840e2932411b6c01031beb2),
<     with modifications to allow tracking allocations / deallocations via Tracy.
<
< *******************************************************************************/
<
< module agora.utils.gc.GC;
<
< import agora.utils.TracyAPI;
---
> /**
>  * Contains the garbage collector implementation.
>  *
>  * Copyright: D Language Foundation 2001 - 2021.
>  * License:   $(HTTP www.boost.org/LICENSE_1_0.txt, Boost License 1.0).
>  * Authors:   Walter Bright, David Friedman, Sean Kelly
>  */
> module core.internal.gc.impl.conservative.gc;
40,42c35,36
< import agora.utils.gc.bits;
< import agora.utils.gc.os;
<
---
> import core.internal.gc.bits;
> import core.internal.gc.os;
45d38
< import core.gc.registry;
47a41,42
> import core.internal.spinlock;
> import core.internal.gc.pooltable;
118c113
< extern(C) pragma(crt_constructor) void _d_register_tracking_conservative_gc()
---
> extern(C) pragma(crt_constructor) void _d_register_conservative_gc()
121c116
<     registerGCFactory("tracking-conservative", &initialize);
---
>     registerGCFactory("conservative", &initialize);
124c119
< extern(C) pragma(crt_constructor) void _d_register_tracking_precise_gc()
---
> extern(C) pragma(crt_constructor) void _d_register_precise_gc()
127c122
<     registerGCFactory("tracking-precise", &initialize_precise);
---
>     registerGCFactory("precise", &initialize_precise);
512d506
<         ___tracy_emit_memory_alloc_callstack(p, size, 32, true);
2763d2756
<                                     ___tracy_emit_memory_free(sentinel_add(p), true);
4701,4706d4693
<             if (OPFAIL != current.find(p))
<             {
<                 debug(PRINTF) printf("Memory allocation without free'ing at %p\n", p);
<                 return;
<             }
<
```

Command used: `diff source/agora/utils/gc/GC.d ~/projects/dlang/druntime/src/core/internal/gc/impl/conservative/gc.d`

Notable in the diff:
- The name change in `atfork` handlers is not needed because, the functions being `extern (C)` but `static` functions in a `struct`, they are mangled anyway;
- The `hasFinalizer` hack should not be needed thanks to https://github.com/dlang/druntime/commit/6558d800f8b4db57bb8954511b7c5987590a0480

2022-03-04 03:47 UTC, Geod24 commented
We probably should build `traced-server` configuration to avoid any regression.

2022-03-04 05:30 UTC, Geod24 commented
Okay, original diff missed a few imports, works just fine now.

2022-03-04 09:43 UTC, mkykadir commented
Brokes Tracy with improper instrumentation

2022-03-04 14:37 UTC, mkykadir requested changes
These are needed for Tracy to work properly

2022-03-04 14:37 UTC, mkykadir commented on source/agora/utils/gc/GC.d
> -        ___tracy_emit_memory_free(sentinel_add(p), true);
This should stay

2022-03-04 14:37 UTC, mkykadir commented on source/agora/utils/gc/GC.d
> -                        ___tracy_emit_memory_free(q, true);
This should stay

2022-03-04 14:37 UTC, mkykadir commented on source/agora/utils/gc/GC.d
>                                      ___tracy_emit_memory_free(sentinel_add(p), true);
```suggestion
                                    ___tracy_emit_memory_free(q, true);
```

2022-03-04 14:37 UTC, mkykadir commented on source/agora/utils/gc/GC.d
> +                        bool doLoop = false;
```suggestion
                        bool doLoop = true;
```

2022-03-04 14:37 UTC, mkykadir commented on source/agora/utils/gc/GC.d
>                                      ___tracy_emit_memory_free(sentinel_add(p), true);
Not mandatory, but suggested

2022-03-14 03:06 UTC, Geod24 commented on source/agora/utils/gc/GC.d
> +                        bool doLoop = false;
As mentioned on Slack, this is the only comment I'm curious about: `version (assert)` should be `true` so this diff shouldn't be needed.

2022-03-14 03:07 UTC, Geod24 commented
Fixed the accidental removal that @mkykadir caught. Just one outstanding comment.

2022-03-14 18:53 UTC, mkykadir commented on source/agora/utils/gc/GC.d
> +                        bool doLoop = false;
This seems not necessary, tried

2022-03-14 18:53 UTC, mkykadir approved these changes

2022-03-14 21:54 UTC, merged