Emit only error logging during unittests
bosagora/agora pull request #72
Opened 2019-07-05 09:17 UTC by AndrejMitrovic

2019-07-05 10:01 UTC, Geod24 commented on source/agora/node/Node.d
> +        setLogLevel(config.logging.log_level);
No!

2019-07-05 10:02 UTC, Geod24 requested changes
The `Node` constructor is not the place to do this. `setLogLevel` affects global data and there might be multiple instances of `Node`, two things which are essentially incompatible.

2019-07-05 12:19 UTC, AndrejMitrovic commented
hmm.. damn global data. I forgot about that.

2019-07-08 00:27 UTC, AndrejMitrovic commented
Updated. I've changed it to set the error level in `makeTestNetwork`, since it appears to be the entry-point to all networking-related unittests.

The calling code can then easily set it to something else via another `setLogLevel` call.

2019-07-08 00:28 UTC, Geod24 approved these changes

2019-07-08 00:45 UTC, merged