Set the limit on the validator cycle
bosagora/agora pull request #973
Opened 2020-06-18 07:46 UTC by linked0

We have made the consensus-critical constants set through a parameter in the last sprint. By the way, developers could set the validator cycle to a value smaller than the `RevealPreimagePeriod` value inadvertently, which make the developers not to be able to find the cause of failures about tests of revealing pre-images.

So I set the restriction that the value must be equal to or greater than the validator cycle.

2020-06-18 07:48 UTC, AndrejMitrovic commented
But this is strictly not a consensus parameter.. How often a node wants to reveal preimages doesn't change consensus rules.

2020-06-18 08:09 UTC, linked0 commented
> But this is strictly not a consensus parameter.. How often a node wants to reveal preimages doesn't change consensus rules.

I know that. But the code is only relevant when unit tests are running and making a new file for that is over-kill.

2020-06-18 08:29 UTC, AndrejMitrovic commented
Isn't it supposed to be configurable by the users too? CC @Geod24 

Then I would suggest moving it to the node config.

2020-06-18 08:49 UTC, linked0 commented
> Isn't it supposed to be configurable by the users too? CC @Geod24
> 
> Then I would suggest moving it to the node config.

Do we have to have another parameter class for non-critical constants and another task for propagating the values with a parameter? If we do that, the `assert` statement can be moved to the `EnrollmentManager`.

2020-06-19 07:52 UTC, Geod24 requested changes
As mentioned, this is not consensus-critical, and should be user-configurable through the config file. Only things that would cause *consensus failure* (two connected well-behaving nodes failing to reach agreement) should go in `ConsensusParams`.

2020-06-19 08:20 UTC, linked0 commented
> As mentioned, this is not consensus-critical, and should be user-configurable through the config file. Only things that would cause _consensus failure_ (two connected well-behaving nodes failing to reach agreement) should go in `ConsensusParams`.

Right, I agree with @Geod24 and @AndrejMitrovic on the non-consensus-critical constant. I will make an assert statement in unit test code, which sets the restriction that the validator cycle above 12 which is `PreimageRevealPeriod * 2`. You know, the value smaller than 12 will make a revelation of pre-images fail.

2020-06-19 08:48 UTC, AndrejMitrovic commented
So why not move this parameter to `NodeConfig` and then move the assert to the node's constructor?

2020-06-19 08:56 UTC, linked0 commented
> So why not move this parameter to `NodeConfig` and then move the assert to the node's constructor?

Yes, I can. Before making that value configurable(#520 ), I will do a quick fix in a proper way.

2020-06-26 05:22 UTC, linked0 commented
I found out the right approach and will apply it to another PR. So I'm closing it.

2020-06-26 05:22 UTC, closed without merging